version: '3.7'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - NODE_ENV=production
    ports:
      - "4000:4000"
    restart: on-failure

  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: on-failure
